package com.threading;

public class ThreadDemo1 extends Thread{
	public void run() {
		String threadname=Thread.currentThread().getName();
		for(int i=0;i<10;i++) {
			System.out.println(i+" generated by "+threadname);
			try {
				Thread.sleep(2000);
			} catch (InterruptedException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
	}
	public static void main(String[] args) throws InterruptedException {
		System.out.println(Thread.currentThread().getName());
		ThreadDemo1 demo1=new ThreadDemo1();
		demo1.setName("Sai1");
		ThreadDemo1 demo2=new ThreadDemo1();
		demo2.setName("Sai2");
		ThreadDemo1 demo3=new ThreadDemo1();
		demo3.setName("Sai3");
		//start thread1 immediately
		demo1.start();
		//start thread2 after completion of thread1
		demo1.join();
		demo2.start();
		//start thread3 after completion of thread2
		demo2.join();
		demo3.start();
		demo1.setPriority(MAX_PRIORITY);
	}
}
